### ISSUE TITLE
"Context sensitive extrude" bug in 2.83 LTS

### ISSUE THREAD

**Issue by 0z3l07** [HEAVYPOLY/HEAVYPOLY_Blender#1]
This works on 2.9 but not on 2.83 LTS
Nothing selected will create a single vert no problem. It works for edges too
But when you try to extrude a face it will only perform the shrink fatten and not extrude. So you only push up and down the face without extruding it. Maybe you can take a look pls :)

**Comment by HEAVYPOLY** [comment]
Hi, the scripts are only supported for daily build. (2.90+)
