### ISSUE TITLE
Boolean Pie breaks on 3.0 Beta

### ISSUE THREAD

**Issue by GreyLambert** [HEAVYPOLY/HEAVYPOLY_Blender#10]
Hey Vaughan Thanks as always for the excellent work. it seems boolean and pie menus break on the latest blender (3.0 beta etc) Is there a way to fix it?
![error dellme](https://user-images.githubusercontent.com/94971963/143242997-d33cadc4-e08e-4bb7-b574-41ad5ac89be0.jpg)

**Comment by HEAVYPOLY** [comment]
Yes, in that script file you could delete the line
cutter.cycles_visibility.camera = False and it should work

Best,

Vaughan Ling

www.HEAVYPAINT.com

**Comment by GreyLambert** [comment]
U Gangster!

that did the trick. thanks a lot! ill comment on the youtube video for others to see. 

have a great day!
Dan

**Comment by HEAVYPOLY** [comment]
Fixed by #aef151560b7ea167cf78e17cd7e72a723eef9909
