### ISSUE TITLE
UV unwrapping trouble.

### ISSUE THREAD

**Issue by alziepen** [HEAVYPOLY/HEAVYPOLY_Blender#11]
Hi Vaughan I'm using blender 3.0 and I noticed that I've never been able to project or unwrap a UV map whilst using the heavypoly config, even on previous builds. Even when using nodes I can't seem to preview the UV's or manipulate them at all. I can do it fine in blender vanilla so I'm not sure if it's intentional or not. 

Hope this helps.

**Comment by HEAVYPOLY** [comment]
you can change the image viewport to UV edit viewport to see the UVs

**Comment by alziepen** [comment]
Doh! I knew it was something on my end. Thanks!!
