### ISSUE TITLE
Drag Select Errors

### ISSUE THREAD

**Issue by RieMars** [HEAVYPOLY/HEAVYPOLY_Blender#17]
(fresh install of 3.3 latest build and today's Heavypoly tools)
When trying to drag select some vertexes, it seems it starts some kind of mode but it ends up doing nothing. Then locks you out of single click selecting in the 3D Viewport until you press ESC.

**Comment by HEAVYPOLY** [comment]
Confirmed here, thanks

**Comment by MadFox09** [comment]
Same problem on 3.2 stable.

**Comment by HEAVYPOLY** [comment]
Fixed by 8915c58 ,let me know if it works!

**Comment by RieMars** [comment]
Thanks! Back in action. I also ended up going through the preferences and changing it from Box Select to Lasso Select just because that one's just a bit more useful for me.
Under prefs > Keymap, I replaced Mesh: view3d.select_through_border (Left Mouse) with view3d.select_lasso (Left Mouse)
