### ISSUE TITLE
Ctrl+S -> Save crashes Blender when the file hasn't been Save-As'ed yet.

### ISSUE THREAD

**Issue by keithyong** [HEAVYPOLY/HEAVYPOLY_Blender#3]
Ctrl+S -> Save crashes Blender when the file hasn't been Save-As'ed yet. Easily replicable by making a new file and doing Ctrl S -> Save without saving-as the file first. Blender version 2.91

**Comment by HEAVYPOLY** [comment]
I'm not getting this crash with latest nightly build of 2.91 + latest HP scripts

**Comment by keithyong** [comment]
Ok you're right running as administrator in windows fixed it 👍

**Comment by HEAVYPOLY** [comment]
Fixed by 
#2101d1b
